language:
- python
python:
- '2.7'
sudo: required
services:
- docker
env:
  global:
  - DATA_API_VERSION: latest
  - DOCKER_USERNAME=edxbuilder
  - secure: ZnwVkXEPIwCFpU5tp85Uxw3TRqS7KhZjkzKEq18tlvN96Ux1ztF9ZeXH6Lz7HK9BXN3m2Z4LCdNYiDkYml90PBjePjLgjmfUmJUcJQsgzhY9ITpuTYlvikHaKa+gVgBOPXsTZJqM2nmCW8WhgoYIl4Y2GnVSh9XdZGvEfiXyNXk=
before_install:
- python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
- docker-compose -f .travis/docker-compose-travis.yml up -d
- docker exec analytics_api bash -c " source /edx/app/analytics_api/venvs/analytics_api/bin/activate
  && make -C /edx/app/analytics_api/analytics_api travis"
- rm package-lock.json
install:
- pip install -r requirements/travis.txt
script:
- docker exec -t -e TRAVIS=1 insights_testing bash -c " cd /edx/app/insights/edx_analytics_dashboard/
  && PATH=\$PATH:/edx/app/insights/nodeenvs/insights/bin:/snap/bin && make $TARGETS
  "
matrix:
  include:
  - python: 3.5
    env: TESTNAME=quality-and-js TARGETS="requirements.js quality validate_js"
    after_success:
    - codecov --disable pycov
  - python: 3.5
    env: TESTNAME=a11y TARGETS="requirements.a11y migrate requirements.js static accept
      a11y"
  - python: 3.5
    env: TESTNAME=test-i18n TARGETS="validate_translations generate_fake_translations"
  - python: 3.5
    env: TESTNAME=test-python TARGETS="requirements.js test_python"
    after_success:
    - docker exec insights_testing /edx/app/insights/edx_analytics_dashboard/.travis/run_coverage.sh
    - codecov --disable pycov
after_failure:
- docker ps
deploy:
- provider: s3
  access_key_id: "$S3_ACCESS_KEY_ID"
  secret_access_key: "$S3_SECRET_ACCESS_KEY"
  bucket: "$S3_BUCKET"
  skip_cleanup: true
  local_dir: "$TRAVIS_BUILD_DIR/build-metrics"
  upload_dir: edx-analytics-dashboard/master
  acl: public_read
  on:
    branch: master
    condition: "$TESTNAME = test-python"
- provider: script
  script: make travis_docker_push
  on:
    branch: master
